dist: xenial
language: java
jdk:
- openjdk11

branches:
  only:
  - master

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_install:
- sudo apt-get update --fix-missing && sudo apt-get install ruby ruby-dev build-essential unzip curl git jq vim -y
- curl -L https://omnitruck.chef.io/install.sh | sudo bash -s -- -v 2.4.17 -P chefdk

script:
- ./gradlew clean build

after_success:
- ./gradlew bintrayUpload
- bash <(curl -s https://codecov.io/bash) -t 9dbdd336-0b99-4b04-b019-0066e702d614
